In [1]:
import pandas as pd
print("pandas is working!")

pandas is working!

In [2]:
df = pd.read_csv("sample_dataset.csv")
df.head()

,Customer ID,Name,Surname,Gender,Birthdate,Transaction Amount,Date,Merchant Name,Category
0,752858,Sean,Rodriguez,F,2002-10-20,35.47,2023-04-03,Smith-Russell,Cosmetic
1,26381,Michelle,Phelps,NaN,1985-10-24,2552.72,2023-07-17,"Peck, Spence and Young",Travel
2,305449,Jacob,Williams,M,1981-10-25,115.97,2023-09-20,Steele Inc,Clothing
3,988259,Nathan,Snyder,M,1977-10-26,11.31,2023-01-11,"Wilson, Wilson and Russell",Cosmetic
4,764762,Crystal,Knapp,F,1951-11-02,62.21,2023-06-13,Palmer-Hinton,Electronics

In [3]:
df.isnull().sum()

Customer ID              0
Name                     0
Surname                  0
Gender                5047
Birthdate                0
Transaction Amount       0
Date                     0
Merchant Name            0
Category                 0
dtype: int64

In [4]:
df['Gender'] = df['Gender'].fillna("Unknown")

In [5]:
df['Date'] = pd.to_datetime(df['Date'])
df['Birthdate'] = pd.to_datetime(df['Birthdate'])

In [6]:
df['Age'] = 2026 - df['Birthdate'].dt.year

In [7]:
df['Month'] = df['Date'].dt.month

In [10]:
df.rename(columns={'Transaction Amount': 'Amount'}, inplace=True)

In [11]:
df.head()

,Customer ID,Name,Surname,Gender,Birthdate,Amount,Date,Merchant Name,Category,Age,Month
0,752858,Sean,Rodriguez,F,2002-10-20,35.47,2023-04-03,Smith-Russell,Cosmetic,24,4
1,26381,Michelle,Phelps,Unknown,1985-10-24,2552.72,2023-07-17,"Peck, Spence and Young",Travel,41,7
2,305449,Jacob,Williams,M,1981-10-25,115.97,2023-09-20,Steele Inc,Clothing,45,9
3,988259,Nathan,Snyder,M,1977-10-26,11.31,2023-01-11,"Wilson, Wilson and Russell",Cosmetic,49,1
4,764762,Crystal,Knapp,F,1951-11-02,62.21,2023-06-13,Palmer-Hinton,Electronics,75,6

In [13]:
df['Amount'].sum()

np.float64(22105961.970000003)

In [14]:
df['Amount'].mean()

np.float64(442.1192394)

In [15]:
df.groupby('Category')['Amount'].sum()

Category
Clothing        1319342.47
Cosmetic         876672.44
Electronics     4394092.10
Market          2151134.42
Restaurant       464488.60
Travel         12900231.94
Name: Amount, dtype: float64

In [16]:
df.groupby('Month')['Amount'].sum()

Month
1     2345228.21
2     2148030.95
3     2396963.31
4     2289731.30
5     2460816.56
6     2254592.41
7     2475041.53
8     2391450.20
9     2274245.66
10    1069861.84
Name: Amount, dtype: float64

In [17]:
df.to_csv("cleaned_data.csv", index=False)